Model:
  name: "densenet_se_bfm_caapm_r_auto"
  type: "denseunet_baseline"
  cl_lr: 0.00001
  lr: 0.0001
  cl_epoch: 30
  max_epoch: 100
  batch_size:  64
  denseblock_num: 3
  n_classes: 5
  activation: 'relu'
  init_weight: True
  seblock_pos: 'both' # 'encoder', 'decoder', 'both', 'none'
  Loss:
    Reconstruction_Loss:
      rate: 1.0
      mse_rate: 0.1
      lap_rate: 0.2
      ssim_rate: 0.7
    Recognition_Loss:
      rate: 0.0
    Contrast_Loss:
      rate: 1.0 

Preprocess:
  crop_mode: 'none' # 'none', 'horizon_shrink', 'vertical_shrink' , 'horizon_vertical_shrink'
  padding_mode: 'mirror_pad' # 
  padding_multiple: 8
  normalize_mode: 'min_max'
  random_flip_mode: True
  random_rotate_mode: True
  match_histogram_mode: False

Training:
  dataset_path: "/mnt/ramdisk/cyc_v2"
  root_path: "./model_record/result/${Model.name}"
  lr_csv_path: "${Training.root_path}/${Daytime}_lr.csv"
  save_weight_root: "${Training.root_path}/${Daytime}_epoch_ft"
  loss_csv_path: "${Training.root_path}/${Daytime}_epoch_ft_loss.csv"
  weight_path: ""
  training: True
  debug: False

Testing:
  root_path: ./model_record/testing/${Model.name}"
  dataset_dir: "/mnt/ramdisk/0616_testset_v2"
  result_dir: "./inference_for_all_epoch/0616_testset_v2/${Model.name}/"
  test_result_csv_path: "${Testing.root_path}/${Model.name}_image.csv"
  label_result_csv_path: "${Testing.root_path}/${Model.name}_label.csv"
  valid_result_dir: "${Testing.root_path}/${Daytime}_valid"
  weight_path: ""
  draw_loss: False
  testing: True
  inference_all_epoch_mode: True
  weight_prefix_name: ""